### ISSUE TITLE
TypeError: Cannot read property 'fsPath' of undefined

### ISSUE THREAD

**Issue by raul338** [calvinbaart/vscode-phpstan#6]
Upon installing and having COMPOSER_HOME defined, I get the following error when running Scan for errors

```
[2018-06-30 11:59:22.597] [exthost1] [error] TypeError: Cannot read property 'fsPath' of undefined
	at PHPStan._command.vscode_1.commands.registerCommand (/home/raul/.vscode/extensions/calsmurf2904.vscode-phpstan-0.1.7/out/phpstan.js:22:30)
	at e._executeContributedCommand (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:674:613)
	at e.$executeContributedCommand (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:675:6)
	at e._doInvokeHandler (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:636:832)
	at e._invokeHandler (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:636:550)
	at e._receiveRequest (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:635:631)
	at e._receiveOneMessage (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:635:400)
	at /opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:634:315
	at /opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:637:395
	at /opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:95:432
	at e.fire (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:96:764)
	at Socket.<anonymous> (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20) extension.scanForErrors
```

I'm using:
```
Versión: 1.24.1
Commit: 24f62626b222e9a8313213fb64b10d741a326288
Fecha: 2018-06-13T17:47:35.732Z
Shell: 1.7.12
Representador: 58.0.3029.110
Nodo 7.9.0
Arquitectura x64
```

**Comment by raul338** [comment]
I tought I could use a phar.
I got this error only by calling "Scan for errors" explictly

**Comment by calvinbaart** [comment]
Solved thanks to https://github.com/calvinbaart/vscode-phpstan/pull/7
